name: Auto-merge
on:
  pull_request:
    types: [opened, ready_for_review, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        run: >-
          gh pr merge ${{ github.event.pull_request.number }}
          --repo ${{ github.repository }}
          --merge --auto --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
